import React from 'react';
// import { motion, useSpring, useScroll } from 'framer-motion'

const PrivacyPolicy = () => {
    // const { scrollYProgress } = useScroll();
    // const scaleX = useSpring(scrollYProgress, {
    //     stiffness: 100,
    //     damping: 30,
    //     restDelta: 0.001,
    // })



    return (
        <div className='flex flex-col justify-center items-center w-full  md:my-20 my-10  '>
            {/* <motion.div
                id="scroll-indicator"
                className="fixed top-20 left-0 right-0 h-1 origin-left bg-[#ccc] z-10"
                style={{
                    scaleX,
                }}
            /> */}
            <div className='flex flex-col justify-center items-center max-w-screen-md gap-6 pt-20'>
                <span className='font-inter font-semibold text-base text-[#B93815] '> Current as of 07 Jan 2025</span>
                <h1 className='font-krona font-normal md:text-5xl text-3xl text-center text-[#181D27]'>Privacy Policy</h1>
                <p className='font-inter font-normal md:text-xl text-lg text-[#535862] text-center'>Your privacy is important to us at Bolka.
                    We respect your privacy regarding any information we may collect from you across our website.</p>
            </div>

            <div className='flex flex-col md:w-[720px] md:mt-28 mt-20 gap-7'>
                {/*Div for Introduction*/}
                <div className='flex flex-col gap-4'>
                    <span className='font-krona font-normal md:text-3xl text-2xl text-[#181D27]'>Introduction</span>
                    <p className='font-inter font-normal md:text-lg text-[#535862] '>Bolka AI is a product of Llamaworx Software Pvt Ltd (“Llamaworx”).</p>
                    <p className='font-inter font-normal md:text-lg text-[#535862] '> Llamaworx operates  <a href="https://bolka.ai" className='text-[#DC6803] underline'>https://bolka.ai</a> (hereinafter referred to as “Service” or “Bolka” interchangeably)</p>
                    <p className='font-inter font-normal md:text-lg text-[#535862] '>Our Privacy Policy governs your visit to <a href="https://bolka.ai" className='text-[#DC6803] underline'>https://bolka.ai</a>,
                        <a href=" https://app.bolka.ai" className='text-[#DC6803] underline ml-1'>https://app.bolka.ai</a>,
                        and<a href=" https://demo.bolka.ai" className='text-[#DC6803] underline'> https://demo.bolka.ai</a>,explaining how we collect, safeguard, and disclose information
                        resulting from your use of our services.</p>
                    <p className='font-inter font-normal md:text-lg text-[#535862]'>
                        We use your data to provide and improve our services.
                        By using Bolka AI, you agree to the collection and use of information in accordance with this policy.
                        Unless otherwise defined, the terms used in this Privacy Policy have the same meanings as those in our Terms and Conditions.</p>
                    <p className='font-inter font-normal md:text-lg text-[#535862] '>Our Terms and Conditions (“Terms”) govern all use of Bolka AI services and,
                        together with this Privacy Policy, form your agreement with us ("agreement").</p>

                </div>

                {/*Div for Definitions*/}
                <div className='flex flex-col gap-4'>
                    <span className='font-krona font-normal md:text-3xl text-2xl text-[#181D27]'>Definitions</span>
                    <p className='font-inter font-normal md:text-lg text-[#181D27] text-start'> <span className='font-inter font-bold'>SERVICE</span> means the <a href="https://bolka.ai" className='text-[#DC6803] underline'>https://bolka.ai</a> website,  <a href=" https://app.bolka.ai" className='text-[#DC6803] underline'> https://app.bolka.ai</a>,
                        and <a href=" https://demo.bolka.ai" className='text-[#DC6803] underline'> https://demo.bolka.ai</a> platforms operated by Llamaworx Software Pvt Ltd.
                    </p>
                    <p className='font-inter font-normal md:text-lg text-[#181D27] text-start'>
                        <span className='font-inter font-bold'>PERSONAL DATA  </span>
                        refers to data about a living individual who can be identified from those data
                        (or from those and other information in our possession or likely to come into our possession).
                    </p>
                    <p className='font-inter font-normal md:text-lg text-[#181D27] text-start'>
                        <span className='font-inter font-bold'> USAGE DATA </span>
                        is data collected automatically, either generated by the use of the Service or
                        from the Service infrastructure itself (e.g., the duration of a page visit).
                    </p>
                    <p className='font-inter font-normal md:text-lg text-[#181D27] text-start'>
                        <span className='font-inter font-bold'> COOKIES </span>
                        are small files stored on your device (computer or mobile device)
                        that hold information related to your activity and preferences.
                    </p>
                    <p className='font-inter font-normal md:text-lg text-[#181D27] text-start'>
                        <span className='font-inter font-bold'> DATA CONTROLLER </span>
                        refers to a natural or legal person who (either alone or jointly with others)
                        determines the purposes for which and the manner in which any personal data are, or are to be, processed.
                        For the purpose of this Privacy Policy,  Llamaworx Software Pvt Ltd is the Data Controller of your data.
                    </p>
                    <p className='font-inter font-normal md:text-lg text-[#181D27] text-start'>
                        <span className='font-inter font-bold'> DATA PROCESSORS (OR SERVICE PROVIDERS) </span>
                        are any natural or legal persons who process data on behalf of the Data Controller.
                        We may engage the services of various Service Providers to process your data more effectively.
                    </p>
                    <p className='font-inter font-normal md:text-lg text-[#181D27] text-start'>
                        <span className='font-inter font-bold'>DATA SUBJECT </span>
                        refers to any living individual whose Personal Data is being processed.
                    </p>
                    <p className='font-inter font-normal md:text-lg text-[#181D27] text-start'>
                        <span className='font-inter font-bold'>THE USER </span>
                        is the representative of client company or an individual using our Service.
                        The User corresponds to the Data Subject, whose Personal Data is being processed.
                    </p>
                </div>
                {/*Div for Information Collection and Use*/}
                <div className='flex flex-col gap-4'>
                    <span className='font-krona font-normal md:text-3xl text-2xl text-[#181D27]'>Information Collection and Use</span>
                    <p className='font-inter font-normal md:text-lg text-[#181D27] text-start'>
                        At Bolka AI, we collect various types of data to deliver and continuously enhance our services,
                        ensuring they meet your needs effectively.
                    </p>
                    {/*Data Collected*/}
                    <div className='flex flex-col gap-4'>
                        <span className='font-krona font-normal text-2xl text-[#181D27]'>Types of Data Collected</span>
                        <ol className='list-decimal pl-6 font-inter font-normal md:text-lg text-[#181D27] flex flex-col gap-4'>
                            <li>
                                <h2 className='font-bold text-lg'>Personal Data</h2>
                                <div className='flex flex-col gap-4'>
                                    <p className='text-start'>
                                        To provide our services, we may request certain information that identifies you, such as:
                                    </p>
                                    <ul className='list-disc pl-6'>
                                        <li>Name, email address, and phone number.</li>
                                        <li>Address details, including city, state, postal code, and country.</li>
                                    </ul>
                                    <p className='text-start'>
                                        We may also use your contact details to share updates, newsletters, or promotional materials.
                                        You can opt out of these communications at any time through the unsubscribe option provided in our emails.
                                    </p>
                                </div>
                            </li>
                            <li>
                                <h2 className='font-bold text-lg'>Usage Data</h2>
                                <div className='flex flex-col gap-4'>
                                    <p className='text-start'>
                                        We automatically collect information about how you interact with our platform, which may include:
                                    </p>
                                    <ul className='list-disc pl-6'>
                                        <li>Device details like IP address, browser type, and version.</li>
                                        <li>Pages visited, time spent on the platform, and other diagnostic details.</li>
                                        <li>
                                            When using our services via a mobile device, we may collect information about the device type,
                                            operating system, and unique identifiers.
                                        </li>
                                    </ul>
                                </div>
                            </li>
                            <li>
                                <h2 className='font-bold text-lg'>Location Data</h2>
                                <div className='flex flex-col gap-4'>
                                    <p className='text-start'>
                                        If you grant permission, we may collect and use location data to provide localized features, improve our services,
                                        and tailor your experience. Location services can be enabled or disabled in your device settings.
                                    </p>
                                </div>
                            </li>
                            <li>
                                <h2 className='font-bold text-lg'>Cookies and Tracking Technologies</h2>
                                <div className='flex flex-col gap-4'>
                                    <p className='text-start'>
                                        We utilize cookies and similar tools to enhance your experience by remembering preferences, tracking activity,
                                        and improving the platform's functionality.
                                    </p>
                                    <span className='font-medium italic'>Types of Cookies We Use:</span>
                                    <ul className='list-disc pl-6'>
                                        <li>Session Cookies: Maintain session continuity.</li>
                                        <li>Preference Cookies: Save your settings and preferences.</li>
                                        <li>Security Cookies: Protect your account and ensure platform safety.</li>
                                        <li>Advertising Cookies: Deliver relevant ads based on your interests.</li>
                                    </ul>
                                    <p className='text-start'>
                                        You can configure your browser to block cookies, but this may limit certain features of the platform.
                                    </p>
                                </div>
                            </li>
                        </ol>
                    </div>
                </div>

                {/*Platform Data*/}
                <div className='flex flex-col gap-4'>
                    <span className='font-krona font-normal md:text-3xl text-2xl text-[#181D27]'>Platform Data</span>
                    <p className='font-inter font-normal md:text-lg text-[#181D27] text-start'>
                        Bolka AI enables businesses to create and manage conversational AI solutions.
                        To deliver our voice AI services, we process specific information:
                    </p>
                    <ol className='list-decimal pl-6 font-inter font-normal md:text-lg text-[#181D27] flex flex-col gap-4'>
                        <li>
                            <span className='font-bold'>AI Assistants</span>
                            <p className='text-start'>
                                You can configure your browser to block cookies, but this may limit certain features of the platform.
                            </p>
                        </li>
                        <li>
                            <span className='font-bold'>Call Data</span>
                            <p className='pl-5 text-start'>
                                We process call audio in real-time, including:
                            </p>
                            <ul className='list-disc pl-6'>
                                <li>Call metadata (e.g., start/end times, duration, and status).</li>
                                <li>Call recordings and transcripts (if enabled).</li>
                                <li>
                                    Logs detailing interactions and responses. Retention of call data is configurable and can be deleted upon request.
                                </li>
                            </ul>
                        </li>
                        <li>
                            <span className='font-bold'>Credentials</span>
                            <p className='text-start'>
                                To enable third-party integrations, we securely store API keys, tokens, and webhooks.
                                These are encrypted and accessible only to authorized systems.
                            </p>
                        </li>
                        <li>
                            <span className='font-bold'>Phone Numbers</span>
                            <p className='text-start'>
                                For inbound and outbound calling, we store assigned phone numbers and related metadata, such as type, provider, and region.
                            </p>
                        </li>
                    </ol>
                </div>

                {/*Other Data*/}
                <div className='flex flex-col gap-4'>
                    <span className='font-krona font-normal md:text-3xl text-2xl text-[#181D27]'>Other Data</span>
                    <span className='font-inter font-normal md:text-lg text-[#181D27] text-start'>Depending on your interactions, we may collect additional information, such as:</span>
                    <ul className=' font-inter font-normal md:text-lg text-[#181D27] text-start list-disc pl-6'>
                        <li>Call metadata (e.g., start/end times, duration, and status).</li>
                        <li>Call recordings and transcripts (if enabled).</li>
                        <li>
                            Logs detailing interactions and responses. Retention of call data is configurable and can be deleted upon request.
                        </li>
                    </ul>
                    <p className='font-inter font-normal md:text-lg text-[#181D27] text-start'>
                        We comply with regulations like GDPR and ensure your data is handled responsibly and securely.
                    </p>
                    <p className='font-inter font-normal md:text-lg text-[#181D27] text-start'>
                        This policy outlines our commitment to safeguarding your information while delivering a seamless and efficient user experience.
                    </p>
                </div>

                {/*Use of data*/}
                <div className='flex flex-col gap-4'>
                    <span className='font-krona font-normal md:text-3xl text-2xl text-[#181D27]'>Use of Data</span>
                    <p className='font-inter font-normal md:text-lg text-[#181D27] text-start'>
                        Bolka AI by Llamaworx Software Pvt Ltd uses the data collected for various purposes to ensure a seamless, secure,
                        and efficient user experience.These purposes include:
                    </p>
                    <ul className=' font-inter font-normal md:text-lg text-[#181D27] text-start list-disc pl-6'>
                        <li>Delivering and maintaining our services.</li>
                        <li>Informing you of updates, changes, or improvements to our platform.</li>
                        <li>Enabling you to access interactive features within our services when opted for.</li>
                        <li>Providing timely and effective customer support.</li>
                        <li>Collecting insights and conducting analysis to enhance service quality and user experience.</li>
                        <li>Monitoring and improving platform performance and usability.</li>
                        <li>Identifying and resolving technical issues to ensure service reliability.</li>
                        <li>Fulfilling contractual obligations and enforcing rights, including billing and payment collections.</li>
                        <li>Sending notifications about your account or subscription, such as expiration alerts, renewal notices, and other instructions.</li>
                        <li>Sharing news, promotions, or updates about related services or events that may interest you, provided you have not opted out of such communications.</li>
                        <li>Using data for any specific purpose disclosed at the time of collection.</li>
                        <li>Processing data for additional purposes only with your explicit consent.</li>
                    </ul>
                    <p className='font-inter font-normal md:text-lg text-[#181D27] text-start'>
                        Your data helps us continually improve our services and align them with your expectations while
                        maintaining compliance with applicable privacy standards.
                    </p>
                </div>

                {/*Retention of Data */}
                <div className='flex flex-col gap-4'>
                    <span className='font-krona font-normal md:text-3xl text-2xl text-[#181D27]'>Retention of Data</span>
                    <p className='font-inter font-normal md:text-lg text-[#181D27] text-start'>
                        Bolka AI by Llamaworx Software Pvt Ltd will retain your Personal Data only for as long as necessary to fulfill the purposes outlined in this Privacy Policy.
                        We may retain and use your Personal Data to:
                    </p>
                    <ul className=' font-inter font-normal md:text-lg text-[#181D27] text-start list-disc pl-6'>
                        <li>Comply with applicable legal and regulatory obligations.</li>
                        <li>Resolve disputes and address user concerns.</li>
                        <li>Enforce our agreements, policies, and terms of service.</li>
                    </ul>
                    <p className='font-inter font-normal md:text-lg text-[#181D27] text-start'>
                        Usage Data is generally retained for shorter periods, primarily for internal analysis and improving platform functionality. However,
                        we may retain Usage Data for extended periods if necessary to:
                    </p>
                    <ul className=' font-inter font-normal md:text-lg text-[#181D27] text-start list-disc pl-6'>
                        <li>Enhance the security and reliability of our services.</li>
                        <li>Comply with legal or regulatory requirements.</li>
                    </ul>
                    <p className='font-inter font-normal md:text-lg text-[#181D27] text-start'>
                        Once data is no longer needed for these purposes, it will be securely deleted or anonymized to ensure your privacy is protected.
                    </p>
                </div>

                {/* Transfer of Data*/}
                <div className='flex flex-col gap-4'>
                    <span className='font-krona font-normal md:text-3xl text-2xl text-[#181D27]'>Transfer of Data</span>
                    <p className='font-inter font-normal md:text-lg text-[#181D27] text-start'>
                        Your information, including Personal Data, may be transferred to and stored on servers or systems located outside your state,
                        province, country, or other jurisdiction where data protection laws may differ from those in your region.
                    </p>
                    <p className='font-inter font-normal md:text-lg text-[#181D27] text-start'>
                        If you choose to provide information to us, please note that your data may be transferred to and processed in locations
                        where <span className=' font-inter font-bold text-lg text-[#DC6803]'> Bolka AI by Llamaworx Software Pvt Ltd</span> or its service providers operate. By using our services
                        and submitting your information, you consent to this transfer and processing in accordance with this Privacy Policy.
                    </p>
                    <p className='font-inter font-normal md:text-lg text-[#181D27] text-start'>
                        We ensure that your data is treated securely and in compliance with this Privacy Policy. No transfer of your Personal Data will occur unless adequate safeguards are in place,
                        including measures to protect the confidentiality and security of your data.
                    </p>
                </div>

                {/*Disclosure of Data */}
                <div className='flex flex-col gap-4'>
                    <span className='font-krona font-normal md:text-3xl text-2xl text-[#181D27]'>Disclosure of Data</span>
                    <p className='font-inter font-normal md:text-lg text-[#181D27] text-start'>
                        Bolka AI by Llamaworx Software Pvt Ltd may disclose your Personal Data in the following circumstances:
                    </p>
                    <ol className='list-decimal pl-6 font-inter font-normal md:text-lg text-[#181D27] flex flex-col gap-4'>
                        <li>
                            <span className='font-bold'>Legal Obligations</span>
                            <p className='text-start'>
                                We may be required to disclose your Personal Data in response to valid legal requests from public authorities,
                                including to comply with laws, regulations, or court orders.
                            </p>
                        </li>
                        <li>
                            <span className='font-bold'>Business Transactions</span>
                            <p className='pl-5 text-start'>
                                In the event of a merger, acquisition, or sale of assets,
                                your Personal Data may be transferred to the involved parties to ensure continuity of service.
                            </p>
                        </li>
                        <li>
                            <span className='font-bold'>Other Situations</span>
                            <div className='flex flex-col gap-4'>
                                <p className='text-start'>
                                    We may also disclose your information:
                                </p>
                                <ul className='list-disc pl-6'>
                                    <li>To our subsidiaries and affiliates for legitimate business purposes.</li>
                                    <li>To fulfill the specific purpose for which you provided the data.</li>
                                    <li>
                                        For any additional purposes explicitly disclosed to you at the time of data collection.
                                    </li>
                                    <li>With your consent, in other instances where sharing your data is necessary.</li>
                                    <li>When necessary to protect the rights, property, or safety of our company, customers, or others.</li>
                                </ul>
                                <p className='text-start'>
                                    We ensure that any disclosure of data aligns with applicable privacy laws and
                                    is carried out responsibly to safeguard your interests.
                                </p>
                            </div>
                        </li>
                    </ol>
                </div>
                {/*Security of Data */}
                <div className='flex flex-col gap-4'>
                    <span className='font-krona font-normal md:text-3xl text-2xl text-[#181D27]'>Security of Data</span>
                    <p className='font-inter font-normal md:text-lg text-[#181D27] text-start'>
                        The security of your data is a priority for Bolka AI by Llamaworx Software Pvt Ltd. We implement industry-standard measures to protect your Personal Data from unauthorized access,
                        disclosure, alteration, or destruction.
                    </p>
                    <p className='font-inter font-normal md:text-lg text-[#181D27] text-start'>
                        However, it is important to note that no method of transmission over the Internet or method of electronic storage can be guaranteed to be 100% secure. While we strive to use robust and
                        commercially acceptable methods to safeguard your data, we cannot ensure or warrant its absolute security.
                    </p>
                    <p className='font-inter font-normal md:text-lg text-[#181D27] text-start'>
                        We continuously monitor and improve our security practices to minimize risks and protect your privacy.
                    </p>
                    <span className='font-krona font-normal text-2xl text-[#181D27]'>
                        Your Data Protection Rights Under General Data Protection Regulation (GDPR)
                    </span>
                    <p className='font-inter font-normal md:text-lg text-[#181D27] text-start'>
                        If you are a resident of the European Union (EU) or European Economic Area (EEA), you have specific rights under the General Data Protection Regulation (GDPR) regarding your Personal Data.
                        These rights aim to give you greater control over how your information is collected, stored, and used.
                    </p>
                    <p className='font-inter font-normal md:text-lg text-[#181D27] text-start'>
                        We are committed to respecting your data protection rights and taking reasonable steps to allow you to access,
                        amend, delete, or restrict the processing of your Personal Data.
                    </p>
                    <p className='font-inter font-normal md:text-lg text-[#181D27] text-start'>Your Rights Include:</p>
                    <ol className='list-decimal pl-6 font-inter font-normal md:text-lg text-[#181D27] flex flex-col gap-4'>
                        <li>
                            <span className='font-bold'>Right to Access, Update, or Delete</span>
                            <ul className='list-disc pl-6'>
                                <li className='text-start'>
                                    You can request access to the Personal Data we hold about you, ask for corrections to inaccurate or incomplete information,
                                    or request the deletion of your data.
                                </li>
                            </ul>
                        </li>
                        <li>
                            <span className='font-bold'>Right of Rectification</span>
                            <ul className='list-disc pl-6'>
                                <li className='text-start'>
                                    You can have your Personal Data corrected if it is found to be inaccurate or incomplete.
                                </li>
                            </ul>
                        </li>
                        <li>
                            <span className='font-bold'>Right to Object</span>
                            <ul className='list-disc pl-6'>
                                <li className='text-start'>
                                    You can object to the processing of your Personal Data for certain purposes, such as marketing.
                                </li>
                            </ul>
                        </li>
                        <li>
                            <span className='font-bold'>Right to Restriction</span>
                            <ul className='list-disc pl-6'>
                                <li className='text-start'>
                                    You can request that we limit the processing of your Personal Data under certain circumstances.
                                </li>
                            </ul>
                        </li>
                        <li>
                            <span className='font-bold'>Right to Data Portability</span>
                            <ul className='list-disc pl-6'>
                                <li className='text-start'>
                                    You can request a copy of your Personal Data in a structured, machine-readable format and transfer it to another data controller.
                                </li>
                            </ul>
                        </li>
                    </ol>
                    <span className='font-krona font-normal text-2xl text-[#181D27]'>
                        How to Exercise Your Rights
                    </span>
                    <p className='font-inter font-normal md:text-lg text-[#181D27] text-start'>
                        To exercise these rights or inquire about the Personal Data we hold about you, please contact us at <a href="mailto:contact@llamaworx.com" className='text-[#DC6803] underline'>contact@llamaworx.com</a>.
                        For verification purposes, we may require additional information to confirm your identity.
                        <span className='block'>Please note that some data is necessary to provide our services, and certain rights may be limited based on legal or contractual obligations.</span>
                    </p>
                    <span className='font-krona font-normal text-2xl text-[#181D27]'>
                        Complaints
                    </span>
                    <p className='font-inter font-normal md:text-lg text-[#181D27] text-start'>
                        If you believe we have not addressed your concerns about your data rights, you have the right to file a complaint with your local Data Protection Authority in the EU or EEA.
                        For more information, contact your local authority.
                        <span className='block'>We are committed to protecting your rights and ensuring your data is handled in compliance with GDPR.</span>
                    </p>
                    <span className='font-krona font-normal text-2xl text-[#181D27]'>
                        Your Data Protection Rights Under Digital Personal Data Protection Act (DPDP) of India
                    </span>
                    <p className='font-inter font-normal md:text-lg text-[#181D27] text-start'>
                        If you are a resident of India, your data is protected under the<span className='font-bold font-inter'> Digital Personal Data Protection Act (DPDP),</span> which governs the collection, processing, and storage of personal information.
                        We are committed to respecting your data protection rights and enabling you to exercise control over your Personal Data.
                    </p>
                    <span className='font-krona font-normal text-2xl text-[#181D27]'>
                        Your Rights Include:
                    </span>
                    <ol className='list-decimal pl-6 font-inter font-normal md:text-lg text-[#181D27] flex flex-col gap-4'>
                        <li>
                            <span className='font-bold'>Right to Access, Update, or Delete</span>
                            <ul className='list-disc pl-6'>
                                <li className='text-start'>
                                    You can request access to the Personal Data we hold about you, ask for corrections to inaccurate or incomplete information,
                                    or request the deletion of your data.
                                </li>
                            </ul>
                        </li>
                        <li>
                            <span className='font-bold'>Right of Rectification</span>
                            <ul className='list-disc pl-6'>
                                <li className='text-start'>
                                    You can have your Personal Data corrected if it is found to be inaccurate or incomplete.
                                </li>
                            </ul>
                        </li>
                        <li>
                            <span className='font-bold'>Right to Withdraw Consent</span>
                            <ul className='list-disc pl-6'>
                                <li className='text-start'>
                                    If you have given consent for the processing of your Personal Data, you can withdraw it at any time.
                                    Withdrawal will not affect the legality of processing carried out prior to your consent withdrawal.
                                </li>
                            </ul>
                        </li>
                        <li>
                            <span className='font-bold'>Right to Grievance Redressal</span>
                            <ul className='list-disc pl-6'>
                                <li className='text-start'>
                                    You can file a grievance with us if you believe your data rights are being violated. If unsatisfied,
                                    you may escalate your complaint to the Data Protection Board of India.
                                </li>
                            </ul>
                        </li>
                        <li>
                            <span className='font-bold'>Right to Nominate</span>
                            <ul className='list-disc pl-6'>
                                <li className='text-start'>
                                    You can nominate an individual to exercise your rights in the event of your incapacity or death, as prescribed by DPDP regulations.
                                </li>
                            </ul>
                        </li>
                    </ol>
                    <span className='font-krona font-normal text-2xl text-[#181D27]'>
                        How to Exercise Your Rights
                    </span>
                    <p className='font-inter font-normal md:text-lg text-[#181D27] text-start'>
                        To exercise your rights or inquire about the Personal Data we hold, contact us at <a href="mailto:contact@llamaworx.com" className='text-[#DC6803] underline'>contact@llamaworx.com</a>.
                        For verification, we may ask for additional information to confirm your identity.
                        <span className='block'>Please note that some rights may be limited under certain legal or contractual obligations,
                            and specific data may be required to provide our services.</span>
                    </p>

                    <span className='font-krona font-normal text-2xl text-[#181D27]'>
                        Complaints
                    </span>

                    <p className='font-inter font-normal md:text-lg text-[#181D27] text-start'>
                        If you are unsatisfied with the resolution of your grievance, you may escalate the issue to the
                        <span className='font-inter font-bold text-lg '> Data Protection Board of India</span>
                        in accordance with applicable laws.

                    </p>
                    <p className='font-inter font-normal md:text-lg text-[#181D27] text-start'>
                        We are committed to protecting your privacy and ensuring compliance with the DPDP Act of India.
                    </p>
                </div>

                {/*Service Providers */}
                <div className='flex flex-col gap-4'>
                    <span className='font-krona font-normal md:text-3xl text-2xl text-[#181D27]'>Service Providers</span>
                    <p className='font-inter font-normal md:text-lg text-[#181D27] text-start'>
                        To deliver and enhance the services offered by Bolka AI by Llamaworx Software Pvt Ltd,
                        we collaborate with third-party companies and individuals ("Service Providers").
                        These Service Providers assist in facilitating our services, performing service-related tasks,
                        or analyzing usage patterns to improve the platform.
                    </p>
                    <span className='font-krona font-normal md:text-3xl text-2xl text-[#181D27]'>Data Access by Service Providers</span>
                    <p className='font-inter font-normal md:text-lg text-[#181D27] text-start'>Service Providers may have access to your Personal Data strictly for performing their designated tasks on our behalf.
                        They are required to maintain confidentiality and are prohibited from using your data for any other purposes.</p>
                    <p className='font-inter font-normal md:text-lg text-[#181D27] text-start'>
                        For an up-to-date list of our third-party Service Providers, please contact us at  <a href="mailto:contact@llamaworx.com" className='text-[#DC6803] underline'>contact@llamaworx.com</a>

                    </p>
                </div>

                {/*Analytics Providers*/}
                <div className='flex flex-col gap-4'>
                    <span className='font-krona font-normal md:text-3xl text-2xl text-[#181D27]'>Analytics Providers</span>
                    <p className='font-inter font-normal md:text-lg text-[#181D27] text-start'>
                        We use analytics tools to monitor and analyse the use of our platform. These include:
                    </p>
                    <ol className='list-decimal pl-6 font-inter font-normal md:text-lg text-[#181D27] flex flex-col gap-4'>
                        <li>
                            <span className='font-bold'>Google Analytics</span>
                            <ul className='list-disc pl-6'>
                                <li className='text-start'>
                                    Tracks and reports website traffic and user behaviour.
                                </li>
                                <li className='text-start'>For details, visit <a href="https://policies.google.com/privacy?hl=en" className='text-[#DC6803] underline'> Google Privacy & Terms</a>. </li>
                            </ul>
                        </li>
                        <li>
                            <span className='font-bold'>Cloudflare Analytics</span>
                            <ul className='list-disc pl-6'>
                                <li className='text-start'>
                                    Analyzes web traffic while ensuring website security and performance.
                                </li>
                                <li className='text-start'>For more information, see <a href="https://www.cloudflare.com/privacypolicy/" className='text-[#DC6803] underline'> Cloudflare Privacy Policy</a>.</li>
                            </ul>
                        </li>
                        <li>
                            <span className='font-bold'>Segment.io</span>
                            <ul className='list-disc pl-6'>
                                <li className='text-start'>
                                    Provides tools for tracking and understanding user behavior.
                                </li>
                                <li className='text-start'>
                                    Learn more at <a href="https://www.twilio.com/en-us/legal/privacy" className='text-[#DC6803] underline'> Segment.io Privacy Policy</a>.

                                </li>
                            </ul>
                        </li>
                        <li>
                            <span className='font-bold'>Mixpanel</span>
                            <ul className='list-disc pl-6'>
                                <li className='text-start'>
                                    Tracks user interactions and events for improving the platform experience.
                                </li>
                                <li className='text-start'>
                                    Opt-out by visiting <a href="https://docs.mixpanel.com/docs/privacy/protecting-user-data#optout-users" className='text-[#DC6803] underline'> Mixpanel Opt-Out</a>.
                                </li>
                            </ul>
                        </li>
                        <li>
                            <span className='font-bold'>PostHog</span>
                            <ul className='list-disc pl-6'>
                                <li className='text-start'>
                                    Offers tools for tracking and analyzing product usage and user journeys.
                                </li>
                                <li className='text-start'>
                                    See details at <a href="https://posthog.com/privacy" className='text-[#DC6803] underline'> PostHog Privacy Policy</a>.
                                </li>
                            </ul>
                        </li>
                        <li>
                            <span className='font-bold'>Matomo Cloud</span>
                            <ul className='list-disc pl-6'>
                                <li className='text-start'>
                                    A privacy-friendly analytics platform for tracking website usage and improving the platform while respecting user data privacy.
                                </li>
                                <li className='text-start'>
                                    For more details, visit <a href="https://matomo.org/matomo-cloud-privacy-policy/" className='text-[#DC6803] underline'>Matomo Privacy Policy</a>.
                                </li>
                            </ul>
                        </li>
                    </ol>
                    <p className='font-inter font-normal md:text-lg text-[#181D27] text-start'>These tools help us maintain platform performance, understand user behavior,
                        and ensure an optimized experience, all while adhering to strict privacy and security standards.</p>
                    <span className='font-krona font-normal md:text-3xl text-2xl text-[#181D27]'>Payments</span>
                    <p className='font-inter font-normal md:text-lg text-[#181D27] text-start'>
                        We provide paid products and/or services within Service.
                        In that case, we use third-party services for payment processing (e.g. payment processors).
                    </p>

                    <p className='font-inter font-normal md:text-lg text-[#181D27] text-start'>The payment processors we work with are:</p>
                    <li>
                        <span className='font-bold font-inter  text-lg'>Stripe:</span>
                        <span className='font-inter font-normal md:text-lg text-[#181D27] text-start ml-1'>
                            Their Privacy Policy can be viewed at:
                        </span>
                        <a href="https://stripe.com/privacy" className='text-[#DC6803] underline font-inter font-normal md:text-lg ml-1'>https://stripe.com/privacy</a>
                    </li>

                </div>

                {/*Links to Other Sites */}
                <div className='flex flex-col gap-4'>
                    <span className='font-krona font-normal md:text-3xl text-2xl text-[#181D27]'>Links to Other Sites</span>
                    <p className='font-inter font-normal md:text-lg text-[#181D27] text-start'>
                        Our Service may include links to third-party websites or services that are not operated or controlled by <span className='font-inter font-bold text-lg '>Bolka AI by Llamaworx Software Pvt Ltd.</span>

                        If you click on a third-party link, you will be directed to their website.
                    </p>
                    <p className='font-inter font-normal md:text-lg text-[#181D27] text-start'>
                        We strongly encourage you to review the Privacy Policy of every website or service you interact with,
                        as their data handling practices may differ from ours.
                    </p>
                    <p className='font-inter font-normal md:text-lg text-[#181D27] text-start'>
                        Please note that we have no control over and cannot be held responsible for the content, privacy policies, or practices of any third-party websites or services.
                        Your interaction with those sites is solely at your discretion and risk.
                    </p>
                </div>

                {/*Children's Privacy */}
                <div className='flex flex-col gap-4'>
                    <span className='font-krona font-normal md:text-3xl text-2xl text-[#181D27]'>Children's Privacy</span>

                    <p className='font-inter font-normal md:text-lg text-[#181D27] text-start'>
                        Our Services are not intended for individuals under the age of 18 without prior written approval from
                        <span className='font-inter font-bold text-lg '> Llamaworx Software Pvt Ltd.</span>
                    </p>
                    <p className='font-inter font-normal md:text-lg text-[#181D27] text-start'>
                        We do not knowingly collect Personal Data from individuals under 18 years of age ("Children"). If you believe that a child has provided us with Personal Data,
                        please contact us immediately at  <a href="mailto:contact@llamaworx.com" className='text-[#DC6803] underline'>contact@llamaworx.com</a>

                    </p>
                    <p className='font-inter font-normal md:text-lg text-[#181D27] text-start'>
                        If we discover that we have inadvertently collected Personal Data from a child without parental consent or written approval,
                        we will take immediate steps to delete such information from our systems.
                    </p>
                    <p className='font-inter font-normal md:text-lg text-[#181D27] text-start'>
                        Parents or guardians who believe their child has provided us with Personal
                        Data without their consent are encouraged to contact us so we can address the issue promptly.
                    </p>
                </div>
                {/*Changes to This Privacy Policy*/}
                <div className='flex flex-col gap-4'>
                    <span className='font-krona font-normal md:text-3xl text-2xl text-[#181D27]'>Changes to This Privacy Policy</span>
                    <p className='font-inter font-normal md:text-lg text-[#181D27] text-start'>
                        We may revise this Privacy Policy periodically to reflect changes in our practices, services, or legal requirements.
                        Updates to the Privacy Policy will be posted on this page.
                    </p>
                    <p className='font-inter font-normal md:text-lg text-[#181D27] text-start'>
                        In the event of significant changes, we will notify you via email and/or a prominent notice on our Service.
                    </p>
                    <p className='font-inter font-normal md:text-lg text-[#181D27] text-start'>
                        We encourage you to review this Privacy Policy regularly to stay informed about how we protect your Personal Data.
                        Changes to this Privacy Policy will take effect as soon as they are posted on this page.
                    </p>
                </div>
                {/* Contact Us*/}
                <div className='flex flex-col gap-4'>
                    <span className='font-krona font-normal md:text-3xl text-2xl text-[#181D27]'>Contact Us</span>
                    <p className='font-inter font-normal md:text-lg text-[#181D27] text-start'>
                        If you have any questions or concerns about this Privacy Policy or the handling of your Personal Data, please contact us at:
                    </p>
                    <p className='font-inter font-bold text-lg text-[#181D27]'>
                        Email:<a href="mailto:contact@llamaworx.com" className='text-[#DC6803] underline ml-1'>contact@llamaworx.com</a>

                    </p>
                    <p className='font-inter font-normal md:text-lg text-[#181D27] text-start'>
                        We are here to address any inquiries and provide assistance regarding your privacy and data security.
                    </p>
                </div>
            </div>
        </div>
    )
}

export default PrivacyPolicy